apiVersion: v1
kind: Pod
metadata:
  name: executor
  labels:
    app: executor
spec:
  containers:
    - name: executor-pod
      image: "ruohang/executor-sum:testv1.1"
      imagePullPolicy: "IfNotPresent"
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: uds-volume
          mountPath: /tmp
    - name: io-sidecar
      image: "ruohang/iosidecar:testv1.1"
      imagePullPolicy: "IfNotPresent"
      env:
        - name: POD_NAME
          value: "example-0"
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: uds-volume
          mountPath: /tmp
    - name: state-sidecar
      image: "ruohang/statesidecar:testv1.1"
      imagePullPolicy: "IfNotPresent"
      volumeMounts:
        - name: uds-volume
          mountPath: /tmp
  volumes:
    - name: config-volume
      configMap:
        name: my-configmap
    - name: uds-volume
      emptyDir: { }