apiVersion: v1
kind: Pod
metadata:
  name: executor
  labels:
    app: executor
spec:
  containers:
    - name: executor-pod
      image: "executor:testv1"
      imagePullPolicy: "IfNotPresent"
  initContainers:
    - name: input-sidecar
      image: "iosidecar:testv1"
      env:
        - name: KAFKA_BROKER
          value: "host.docker.internal:9092"
      imagePullPolicy: "IfNotPresent"
      restartPolicy: Always
    - name: state-sidecar
      image: "statesidecar:testv1"
      imagePullPolicy: "IfNotPresent"
      restartPolicy: Always
    - name: producer-sidecar
      image: "producersidecar:testv1"
      imagePullPolicy: "IfNotPresent"
      restartPolicy: Always
      env:
        - name: KAFKA_BROKER
          value: "host.docker.internal:9092"